/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/arrow': RouteRecordInfo<'/arrow', '/arrow', Record<never, never>, Record<never, never>>,
    '/use-click': RouteRecordInfo<'/use-click', '/use-click', Record<never, never>, Record<never, never>>,
    '/use-client-point': RouteRecordInfo<'/use-client-point', '/use-client-point', Record<never, never>, Record<never, never>>,
    '/use-dismiss': RouteRecordInfo<'/use-dismiss', '/use-dismiss', Record<never, never>, Record<never, never>>,
    '/use-focus': RouteRecordInfo<'/use-focus', '/use-focus', Record<never, never>, Record<never, never>>,
    '/use-hover': RouteRecordInfo<'/use-hover', '/use-hover', Record<never, never>, Record<never, never>>,
    '/use-list-navigation': RouteRecordInfo<'/use-list-navigation', '/use-list-navigation', Record<never, never>, Record<never, never>>,
    '/use-role': RouteRecordInfo<'/use-role', '/use-role', Record<never, never>, Record<never, never>>,
    '/use-transiton': RouteRecordInfo<'/use-transiton', '/use-transiton', Record<never, never>, Record<never, never>>,
    '/use-typeahead': RouteRecordInfo<'/use-typeahead', '/use-typeahead', Record<never, never>, Record<never, never>>,
  }
}
